n = input('Digite algo:')
print('O tipo primito desse valor é', type(n))
print('Só tem espaços ?', n.isspace())
print('É um número ?', n.isnumeric())
print('É alfabetico ?', n.isalpha())
print('É alfanúmerico ?', n.isalnum())
print('Está em maiúsculas ?', n.isupper())
print('Está em minúsculas ?', n.islower())
print('Está capitalizado ?', n.istitle())
